GET https://api.forms.app/form
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzJkYzlkYTU4NzJkOTVmZTdlZDE0NzQiLCJ0b2tlbnBvbGljeSI6IldlYiIsImVtYWlsIjoia2VuYW4uc2FsaWNAZ21haWwuY29tIiwidXNlcm5hbWUiOiJrZW5hbnNhbGljIiwiZnVsbG5hbWUiOiJLZW5hbiBTYWxpYyIsInRpbWV6b25lIjoiVy4gRXVyb3BlIFN0YW5kYXJkIFRpbWUiLCJjdWx0dXJlIjoibmwtTkwiLCJpc0VtYWlsQ29uZmlybWVkIjoidHJ1ZSIsImhhc1Bhc3N3b3JkIjoiZmFsc2UiLCJjcmVhdGVEYXRlIjoiMjAyMi0wOS0yM1QxNDo1OTozOC45MDZaIiwibmJmIjoxNjYzOTQ1MTc4LCJleHAiOjE2OTUwNDkxNzh9.DoaXyx0lfTpAyyPbZrcUhOvMJTBsuO1bnNmpFSq3Skk